//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Catalog.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Additional {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Additional() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Catalog.Resources.Additional", typeof(Additional).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Батарея должна быть положительным числом, больше нуля и не содержать символов строки!.
        /// </summary>
        internal static string BatteryRES {
            get {
                return ResourceManager.GetString("BatteryRES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Камера должна быть положительным числом, больше нуля и не содержать символов строки!.
        /// </summary>
        internal static string CameraRES {
            get {
                return ResourceManager.GetString("CameraRES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле не должно содержать следующие знаки: &apos;;&apos; &apos;:&apos; &apos;/&apos; &apos;\&apos; &apos;|&apos; &apos;,&apos; &apos;.&apos;..
        /// </summary>
        internal static string ContainsRES {
            get {
                return ResourceManager.GetString("ContainsRES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество должно быть целым положительным числом, больше нуля и не содержать символы строки!.
        /// </summary>
        internal static string CountRES {
            get {
                return ResourceManager.GetString("CountRES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Размер дисплея должен быть положительным числом, больше нуля и не содержать символов строки!.
        /// </summary>
        internal static string DisplaySizeRES {
            get {
                return ResourceManager.GetString("DisplaySizeRES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ссылка на картинку должна содержать &quot;http&quot; и не содержать символы &apos;;&apos;..
        /// </summary>
        internal static string ImageRES {
            get {
                return ResourceManager.GetString("ImageRES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле должно быть заполненным!.
        /// </summary>
        internal static string NotEmptyRES {
            get {
                return ResourceManager.GetString("NotEmptyRES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цена должна быть положительным числом, больше нуля и не содержать символов строки!.
        /// </summary>
        internal static string PriceRES {
            get {
                return ResourceManager.GetString("PriceRES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле не должно содержать следующие знаки: &apos;;&apos; &apos;:&apos; &apos;/&apos; &apos;\&apos; &apos;|&apos; &apos;,&apos; &apos;.&apos;..
        /// </summary>
        internal static string ProcessorRES {
            get {
                return ResourceManager.GetString("ProcessorRES", resourceCulture);
            }
        }
    }
}
